//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LichCongTac
    {
        public int ID { get; set; }
        public string LangCode { get; set; }
        public int UserID { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public string giobatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public string noidung { get; set; }
        public byte allDay { get; set; }
        public byte LVTCQ { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public byte Status { get; set; }
    
        public virtual tbl_UserAdmin tbl_UserAdmin { get; set; }
    }
}
