//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccessView
    {
        public int ID { get; set; }
        public Nullable<int> TongCong { get; set; }
        public System.DateTime NgayThongKe { get; set; }
        public Nullable<int> HomNay { get; set; }
        public Nullable<int> HomTruoc { get; set; }
        public Nullable<int> TuanNay { get; set; }
        public Nullable<int> TuanTruoc { get; set; }
        public Nullable<int> ThangNay { get; set; }
        public Nullable<int> ThangTruoc { get; set; }
    }
}
