//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BoxNewsConfig
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int PageElementId { get; set; }
        public string LangCode { get; set; }
    }
}
