//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TTHC
    {
        public int ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> DonViId { get; set; }
        public Nullable<int> LinhVucId { get; set; }
        public string ThuTuc { get; set; }
        public string LangCode { get; set; }
        public string Attachment { get; set; }
        public string Tieude { get; set; }
        public string TrinhTuThucHien { get; set; }
        public string CachThucThucHien { get; set; }
        public string ThanhPhanHoSo { get; set; }
        public string ThoiHan { get; set; }
        public string DoiTuong { get; set; }
        public string CoQuanThucHien { get; set; }
        public string KetQua { get; set; }
        public string LePhi { get; set; }
        public string TenMauDon { get; set; }
        public string YeuCauDieuKien { get; set; }
        public string CoSoPhapLy { get; set; }
        public int Status { get; set; }
        public long ViewCount { get; set; }
        public Nullable<byte> AllowComment { get; set; }
    }
}
