//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GalleryCategory
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LangCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<int> Ordering { get; set; }
    }
}
